Repository ShallWeProject/ShallWeProject_Server, pull requests merged in 2023-07, with the labels that each got.

#3 [FEAT] 유저 도메인과 Auth 기능을 개발한다.
  src/main/java/com/shallwe/domain/auth/application/AuthService.java
  src/main/java/com/shallwe/domain/auth/application/CustomDefaultOAuth2UserService.java
  src/main/java/com/shallwe/domain/auth/domain/Token.java
  src/main/java/com/shallwe/domain/auth/dto/AuthRes.java
  src/main/java/com/shallwe/domain/auth/dto/RefreshTokenReq.java
  src/main/java/com/shallwe/domain/auth/dto/TokenMapping.java
  src/main/java/com/shallwe/domain/user/domain/Gender.java
  src/main/java/com/shallwe/domain/user/domain/User.java
  src/main/java/com/shallwe/global/config/security/SecurityConfig.java
Labels: chore, feature

#11 #5 [Setting] db생성, yml 설정
  .ebextensions/00-makeFiles.config
  .ebextensions/00-set-timezone.config
  .github/ISSUE_TEMPLATE/bug-template.md
  .github/ISSUE_TEMPLATE/feature-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/deploy.yml
  .gitignore
  .platform/conf.d/cors.conf
  .platform/nginx.conf
  Dockerfile
  Dockerrun.aws.json
  Procfile
  README.md
  build.gradle
  src/main/java/com/shallwe/ShallWeApplication.java
  src/main/java/com/shallwe/global/config/security/WebMvcConfig.java
  src/main/resources/swagger/application-springdoc.yml
Labels: chore, setting

#13 [FEAT] 소셜 로그인 기능을 구현한다.
  src/main/java/com/shallwe/domain/auth/application/CustomDefaultOAuth2UserService.java
  src/main/java/com/shallwe/domain/user/domain/User.java
  src/main/java/com/shallwe/global/config/security/auth/OAuth2UserInfo.java
  src/main/java/com/shallwe/global/config/security/auth/OAuth2UserInfoFactory.java
  src/main/java/com/shallwe/global/config/security/auth/company/Facebook.java
  src/main/java/com/shallwe/global/config/security/auth/company/Github.java
  src/main/java/com/shallwe/global/config/security/auth/company/Google.java
  src/main/java/com/shallwe/global/config/security/auth/company/Kakao.java
  src/main/java/com/shallwe/global/config/security/auth/company/Naver.java
  src/main/java/com/shallwe/global/config/security/handler/CustomSimpleUrlAuthenticationSuccessHandler.java
Labels: feature

#15 #14 setting and refactoring : 프로젝트 초기설정 리펙토링
  .gitignore
  build.gradle
  src/main/java/com/shallwe/domain/auth/application/AuthService.java
  src/main/java/com/shallwe/domain/auth/domain/Token.java
  src/main/java/com/shallwe/domain/user/application/UserService.java
  src/main/java/com/shallwe/domain/user/application/UserServiceImpl.java
  src/main/java/com/shallwe/domain/user/dto/UserDeleteRes.java
  src/main/java/com/shallwe/domain/user/dto/UserRes.java
  src/main/java/com/shallwe/domain/user/exception/DefaultException.java
  src/main/java/com/shallwe/domain/user/exception/DefaultNullPointerException.java
  src/main/java/com/shallwe/domain/user/exception/InvalidParameterException.java
  src/main/java/com/shallwe/domain/user/exception/TokenExpirationException.java
  src/main/java/com/shallwe/domain/user/presentation/UserController.java
  src/main/java/com/shallwe/domain/user/presentation/UserExceptionController.java
  src/main/java/com/shallwe/global/DefaultAssert.java
  src/main/java/com/shallwe/global/controller/ExceptionController.java
  src/main/java/com/shallwe/global/dto/response/ResponseCustom.java
  src/main/java/com/shallwe/global/error/ApiControllerAdvice.java
  src/main/java/com/shallwe/global/error/DefaultException.java
  src/main/java/com/shallwe/global/error/DefaultNullPointerException.java
  src/main/java/com/shallwe/global/error/InvalidParameterException.java
Labels: refactor, setting

#18 [refactor] 프로젝트 예외처리 관련 리펙토링을 한다.
  src/main/java/com/shallwe/domain/user/application/UserServiceImpl.java
  src/main/java/com/shallwe/domain/user/domain/repository/UserRepository.java
  src/main/java/com/shallwe/domain/user/dto/UserDeleteRes.java
  src/main/java/com/shallwe/domain/user/dto/UserRes.java
  src/main/java/com/shallwe/domain/user/exception/DefaultNullPointerException.java
  src/main/java/com/shallwe/domain/user/exception/InvalidParameterException.java
  src/main/java/com/shallwe/domain/user/exception/InvalidTokenException.java
  src/main/java/com/shallwe/domain/user/exception/InvalidUserException.java
  src/main/java/com/shallwe/domain/user/exception/TokenExpirationException.java
  src/main/java/com/shallwe/domain/user/presentation/UserController.java
  src/main/java/com/shallwe/domain/user/presentation/UserExceptionController.java
  src/main/java/com/shallwe/global/DefaultAssert.java
  src/main/java/com/shallwe/global/controller/ExceptionController.java
  src/main/java/com/shallwe/global/error/ApiControllerAdvice.java
  src/main/java/com/shallwe/global/error/DefaultException.java
  src/main/java/com/shallwe/global/error/DefaultNullPointerException.java
  src/main/java/com/shallwe/global/error/InvalidParameterException.java
  src/main/java/com/shallwe/global/payload/ErrorCode.java
  src/main/java/com/shallwe/global/payload/ErrorResponse.java
  src/main/java/com/shallwe/global/payload/Message.java
  src/main/java/com/shallwe/global/payload/ResponseCustom.java
Labels: refactor

#29 #19 dockerfile entrypoint수정
  Dockerfile
Labels: fix

#35 [feat]: 이용약관 동의 / 프로필 정보 입력 API를 구현한다.
  src/main/java/com/shallwe/domain/reservation/application/ReservationServiceImpl.java
  src/main/java/com/shallwe/domain/reservation/exception/DefaultNullPointerException.java
  src/main/java/com/shallwe/domain/reservation/exception/InvalidParameterException.java
  src/main/java/com/shallwe/domain/reservation/exception/InvalidReservationException.java
  src/main/java/com/shallwe/domain/reservation/presentation/ReservationController.java
  src/main/java/com/shallwe/domain/user/application/UserService.java
  src/main/java/com/shallwe/domain/user/application/UserServiceImpl.java
  src/main/java/com/shallwe/domain/user/domain/User.java
  src/main/java/com/shallwe/domain/user/dto/DeleteUserRes.java
  src/main/java/com/shallwe/domain/user/dto/SignUpUserReq.java
  src/main/java/com/shallwe/domain/user/dto/SignUpUserRes.java
  src/main/java/com/shallwe/domain/user/dto/UserDetailRes.java
  src/main/java/com/shallwe/domain/user/presentation/UserController.java
  src/main/java/com/shallwe/domain/user/presentation/UserExceptionController.java
Labels: feature

#31 #30 경험선물 엔티티,mvc패턴 생성
  src/main/java/com/shallwe/domain/experience_gift/application/ExperienceGiftService.java
  src/main/java/com/shallwe/domain/experience_gift/application/ExperienceGiftServiceImpl.java
  src/main/java/com/shallwe/domain/experience_gift/domain/ExpCategory.java
  src/main/java/com/shallwe/domain/experience_gift/domain/ExperienceGift.java
  src/main/java/com/shallwe/domain/experience_gift/domain/SttCategory.java
  src/main/java/com/shallwe/domain/experience_gift/domain/Subtitle.java
  src/main/java/com/shallwe/domain/experience_gift/presentation/ExperienceGiftController.java
  src/main/java/com/shallwe/domain/experience_gift/repository/ExperienceGiftRepository.java
  src/main/java/com/shallwe/domain/reservation/application/ReservationServiceImpl.java
  src/main/java/com/shallwe/domain/reservation/domain/Reservation.java
Labels: feature

#42 #41 경험검색조회, 경험상세조회 기능구현,querydsl설정 추가
  build.gradle
  src/main/generated/com/shallwe/domain/auth/domain/QToken.java
  src/main/generated/com/shallwe/domain/common/QBaseEntity.java
  src/main/generated/com/shallwe/domain/experience_gift/domain/QExpCategory.java
  src/main/generated/com/shallwe/domain/experience_gift/domain/QExperienceGift.java
  src/main/generated/com/shallwe/domain/experience_gift/domain/QSttCategory.java
  src/main/generated/com/shallwe/domain/experience_gift/domain/QSubtitle.java
  src/main/generated/com/shallwe/domain/reservation/domain/QReservation.java
  src/main/generated/com/shallwe/domain/user/domain/QUser.java
  src/main/java/com/shallwe/domain/experience_gift/application/ExperienceGiftService.java
  src/main/java/com/shallwe/domain/experience_gift/application/ExperienceGiftServiceImpl.java
  src/main/java/com/shallwe/domain/experience_gift/domain/ExperienceGift.java
  src/main/java/com/shallwe/domain/experience_gift/dto/ExperienceDetailRes.java
  src/main/java/com/shallwe/domain/experience_gift/dto/ExperienceRes.java
  src/main/java/com/shallwe/domain/experience_gift/exception/ExperienceGiftNotFoundException.java
  src/main/java/com/shallwe/domain/experience_gift/presentation/ExperienceGiftController.java
  src/main/java/com/shallwe/domain/experience_gift/repository/ExperienceGiftRepository.java
  src/main/java/com/shallwe/domain/reservation/application/ReservationServiceImpl.java
  src/main/java/com/shallwe/global/config/querydsl/QueryDslConfig.java
Labels: feature, setting
