Repository ShallWeProject/ShallWeProject_Server, pull requests merged in 2023-12, with the labels that each got.

#183 유저와 사장님 날짜 예약 조회 반환값을 변경한다.
  src/main/java/com/shallwe/domain/reservation/application/ReservationService.java
  src/main/java/com/shallwe/domain/reservation/application/ReservationServiceImpl.java
  src/main/java/com/shallwe/domain/reservation/dto/ReservationIdOwnerRes.java
  src/main/java/com/shallwe/domain/reservation/dto/ReservationIdUserRes.java
  src/main/java/com/shallwe/domain/reservation/dto/ReservationResponse.java
  src/main/java/com/shallwe/domain/reservation/presentation/ReservationController.java
  src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerServiceImpl.java
  src/main/java/com/shallwe/domain/shopowner/presentation/ShopOwnerController.java
Labels: refactor

#185 feat: 사장 신분증/사업자등록증/통장사본 등록 API 구현
  src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerService.java
  src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerServiceImpl.java
  src/main/java/com/shallwe/domain/shopowner/domain/ShopOwner.java
  src/main/java/com/shallwe/domain/shopowner/dto/ShopOwnerIdentificationReq.java
  src/main/java/com/shallwe/domain/shopowner/presentation/ShopOwnerController.java
Labels: feature

#190 스웨거 스키마 수정 및 가능 날짜 조회시 시간을 반환하도록 수정한다.
  src/main/java/com/shallwe/domain/reservation/application/ReservationService.java
  src/main/java/com/shallwe/domain/reservation/application/ReservationServiceImpl.java
  src/main/java/com/shallwe/domain/reservation/dto/ReservationIdOwnerRes.java
  src/main/java/com/shallwe/domain/reservation/dto/ReservationIdUserRes.java
  src/main/java/com/shallwe/domain/reservation/presentation/ReservationController.java
  src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerServiceImpl.java
  src/main/java/com/shallwe/domain/shopowner/presentation/ShopOwnerController.java
Labels: fix

#191 빌드 충돌 오류를 해결한다.
  src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerServiceImpl.java
Labels: bug

#192 feat: MemoryPhoto 삭제 API 구현
  src/main/java/com/shallwe/domain/memoryphoto/application/MemoryPhotoService.java
  src/main/java/com/shallwe/domain/memoryphoto/application/MemoryPhotoServiceImpl.java
  src/main/java/com/shallwe/domain/memoryphoto/domain/MemoryPhoto.java
  src/main/java/com/shallwe/domain/memoryphoto/domain/repository/MemoryPhotoRepository.java
  src/main/java/com/shallwe/domain/memoryphoto/dto/MemoryPhotoDetailRes.java
  src/main/java/com/shallwe/domain/memoryphoto/dto/MemoryPhotoUserDetailRes.java
  src/main/java/com/shallwe/domain/memoryphoto/exception/MemoryPhotoUploaderMismatchException.java
  src/main/java/com/shallwe/domain/memoryphoto/presentation/MemoryPhotoController.java
  src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationQuerydslRepository.java
  src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationQuerydslRepositoryImpl.java
Labels: feature, fix

#194 refactor: 안 쓰는 코드 정리 + 코드 컨벤션대로 수정
  src/main/java/com/shallwe/domain/memoryphoto/application/MemoryPhotoServiceImpl.java
  src/main/java/com/shallwe/domain/memoryphoto/domain/repository/MemoryPhotoRepository.java
  src/main/java/com/shallwe/domain/reservation/application/ReservationServiceImpl.java
  src/main/java/com/shallwe/domain/reservation/domain/Reservation.java
  src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationQuerydslRepository.java
  src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationQuerydslRepositoryImpl.java
  src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationRepository.java
  src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerService.java
  src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerServiceImpl.java
  src/main/java/com/shallwe/domain/shopowner/domain/repository/ShopOwnerRepository.java
  src/main/java/com/shallwe/domain/user/application/UserService.java
  src/main/java/com/shallwe/domain/user/application/UserServiceImpl.java
  src/main/java/com/shallwe/domain/user/domain/repository/UserRepository.java
  src/main/java/com/shallwe/domain/user/dto/ReceiveGiftDetailRes.java
  src/main/java/com/shallwe/domain/user/exception/InvalidPhoneNumberException.java
  src/main/java/com/shallwe/domain/user/exception/InvalidUserException.java
  src/main/java/com/shallwe/domain/user/presentation/UserController.java
Labels: chore, refactor

#196 fix: 받은 유저 선물 조회 API experienceGiftId Response 추가
  src/main/java/com/shallwe/domain/user/dto/ReceiveGiftDetailRes.java
Labels: fix

#198 recfactor: experience gift, reservation 등 코드 컨벤션 적용
  src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftService.java
  src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftServiceImpl.java
  src/main/java/com/shallwe/domain/experiencegift/domain/ExperienceCategory.java
  src/main/java/com/shallwe/domain/experiencegift/domain/ExperienceGift.java
  src/main/java/com/shallwe/domain/experiencegift/domain/ExperienceGiftImage.java
  src/main/java/com/shallwe/domain/experiencegift/domain/Explanation.java
  src/main/java/com/shallwe/domain/experiencegift/domain/SituationCategory.java
  src/main/java/com/shallwe/domain/experiencegift/domain/Subtitle.java
  src/main/java/com/shallwe/domain/experiencegift/domain/repository/ExpCategoryRepository.java
  src/main/java/com/shallwe/domain/experiencegift/domain/repository/ExperienceCategoryRepository.java
  src/main/java/com/shallwe/domain/experiencegift/domain/repository/ExperienceGiftImageRepository.java
  src/main/java/com/shallwe/domain/experiencegift/domain/repository/ExperienceGiftQuerydslRepository.java
  src/main/java/com/shallwe/domain/experiencegift/domain/repository/ExperienceGiftQuerydslRepositoryImpl.java
  src/main/java/com/shallwe/domain/experiencegift/domain/repository/ExperienceGiftRepository.java
  src/main/java/com/shallwe/domain/experiencegift/domain/repository/ExplanationRepository.java
  src/main/java/com/shallwe/domain/experiencegift/domain/repository/SituationCategoryRepository.java
  src/main/java/com/shallwe/domain/experiencegift/domain/repository/SttCategoryRepository.java
  src/main/java/com/shallwe/domain/experiencegift/domain/repository/SubtitleRepository.java
  src/main/java/com/shallwe/domain/experiencegift/dto/request/ExperienceReq.java
  src/main/java/com/shallwe/domain/experiencegift/dto/request/ExplanationReq.java
  src/main/java/com/shallwe/domain/experiencegift/dto/request/ShopOwnerExperienceReq.java
  src/main/java/com/shallwe/domain/experiencegift/dto/response/ExpCategoryRes.java
  src/main/java/com/shallwe/domain/experiencegift/dto/response/ExperienceDetailRes.java
  src/main/java/com/shallwe/domain/experiencegift/dto/response/ExperienceExpCategoryRes.java
  src/main/java/com/shallwe/domain/experiencegift/dto/response/ExperienceMainRes.java
  src/main/java/com/shallwe/domain/experiencegift/dto/response/ExperienceRes.java
  src/main/java/com/shallwe/domain/experiencegift/dto/response/ExperienceSttCategoryRes.java
  src/main/java/com/shallwe/domain/experiencegift/dto/response/ExplanationRes.java
  src/main/java/com/shallwe/domain/experiencegift/dto/response/ShopOwnerExperienceRes.java
  src/main/java/com/shallwe/domain/experiencegift/dto/response/ShopOwnerMainRes.java
  src/main/java/com/shallwe/domain/experiencegift/dto/response/SttCategoryRes.java
  src/main/java/com/shallwe/domain/experiencegift/presentation/ExperienceGiftController.java
  src/main/java/com/shallwe/domain/experiencegift/presentation/ShopOwnerExperienceGiftController.java
  src/main/java/com/shallwe/domain/reservation/application/ReservationService.java
  src/main/java/com/shallwe/domain/reservation/application/ReservationServiceImpl.java
  src/main/java/com/shallwe/domain/reservation/domain/Reservation.java
  src/main/java/com/shallwe/domain/reservation/domain/ReservationStatus.java
  src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationQuerydslRepositoryImpl.java
  src/main/java/com/shallwe/domain/reservation/dto/DeleteReservationRes.java
  src/main/java/com/shallwe/domain/reservation/dto/ReservationIdOwnerRes.java
  src/main/java/com/shallwe/domain/reservation/dto/ReservationIdUserRes.java
  src/main/java/com/shallwe/domain/reservation/dto/ReservationRequest.java
  src/main/java/com/shallwe/domain/reservation/dto/ReservationResponse.java
  src/main/java/com/shallwe/domain/reservation/dto/ReservationUserReq.java
  src/main/java/com/shallwe/domain/reservation/dto/UpdateReservationReq.java
  src/main/java/com/shallwe/domain/reservation/dto/ValidTimeSlotRes.java
  src/main/java/com/shallwe/domain/reservation/presentation/ReservationController.java
  src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerServiceImpl.java
  src/main/java/com/shallwe/domain/shopowner/presentation/ShopOwnerController.java
  src/main/java/com/shallwe/domain/user/dto/ReceiveGiftDetailRes.java
Labels: refactor, fix
