Repository ShallWeProject/ShallWeProject_Server, pull requests merged in 2023-11, with the labels that each got.

#143 [feat] 관리자 경험 상품 등록 API구현
  src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftService.java
  src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftServiceImpl.java
  src/main/java/com/shallwe/domain/experiencegift/domain/ExpCategory.java
  src/main/java/com/shallwe/domain/experiencegift/domain/ExperienceGift.java
  src/main/java/com/shallwe/domain/experiencegift/domain/Explanation.java
  src/main/java/com/shallwe/domain/experiencegift/domain/SttCategory.java
  src/main/java/com/shallwe/domain/experiencegift/domain/Subtitle.java
  src/main/java/com/shallwe/domain/experiencegift/domain/repository/ExpCategoryRepository.java
  src/main/java/com/shallwe/domain/experiencegift/domain/repository/SttCategoryRepository.java
  src/main/java/com/shallwe/domain/experiencegift/domain/repository/SubtitleRepository.java
  src/main/java/com/shallwe/domain/experiencegift/dto/request/AdminExperienceReq.java
  src/main/java/com/shallwe/domain/experiencegift/dto/request/ExplanationReq.java
  src/main/java/com/shallwe/domain/experiencegift/dto/response/ExperienceDetailRes.java
  src/main/java/com/shallwe/domain/experiencegift/dto/response/ExplanationRes.java
  src/main/java/com/shallwe/domain/experiencegift/exception/ChooseOnlyOneCategory.java
  src/main/java/com/shallwe/domain/experiencegift/exception/ExpCategoryAlreadyExist.java
  src/main/java/com/shallwe/domain/experiencegift/exception/SttCategoryAlreadyExist.java
  src/main/java/com/shallwe/domain/experiencegift/presentation/AdminExperienceGiftController.java
Labels: feature

#144 [Feat] 관리자 상품 목록 조회 API구현
  src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftService.java
  src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftServiceImpl.java
  src/main/java/com/shallwe/domain/experiencegift/domain/repository/ExperienceGiftRepository.java
  src/main/java/com/shallwe/domain/experiencegift/dto/response/AdminExperienceRes.java
  src/main/java/com/shallwe/domain/experiencegift/presentation/AdminExperienceGiftController.java
Labels: feature

#145 [Feat] 관리자 메인 페이지 API구현
  src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftService.java
  src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftServiceImpl.java
  src/main/java/com/shallwe/domain/experiencegift/dto/response/AdminMainRes.java
  src/main/java/com/shallwe/domain/experiencegift/presentation/AdminExperienceGiftController.java
  src/main/java/com/shallwe/domain/reservation/domain/ReservationStatus.java
  src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationRepository.java
Labels: feature

#146 충돌 해결
  src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftServiceImpl.java
  src/main/java/com/shallwe/domain/experiencegift/presentation/AdminExperienceGiftController.java
Labels: fix

#148 [feat] 예약 등록 구현 방식을 변경한다.
  src/main/java/com/shallwe/domain/memoryphoto/dto/MemoryPhotoDetailRes.java
  src/main/java/com/shallwe/domain/reservation/application/ReservationServiceImpl.java
  src/main/java/com/shallwe/domain/reservation/domain/Reservation.java
  src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationRepository.java
  src/main/java/com/shallwe/domain/reservation/dto/ReservationRequest.java
  src/main/java/com/shallwe/domain/reservation/dto/ReservationResponse.java
  src/main/java/com/shallwe/domain/reservation/dto/UpdateReservationReq.java
  src/main/java/com/shallwe/domain/reservation/presentation/ReservationController.java
  src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerService.java
  src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerServiceImpl.java
  src/main/java/com/shallwe/domain/shopowner/domain/ShopOwner.java
  src/main/java/com/shallwe/domain/shopowner/dto/ShopOwnerGiftManageRes.java
  src/main/java/com/shallwe/domain/shopowner/dto/ShopOwnerReservationRes.java
  src/main/java/com/shallwe/domain/shopowner/presentation/ShopOwnerController.java
  src/main/java/com/shallwe/domain/user/dto/ReceiveGiftDetailRes.java
  src/main/java/com/shallwe/domain/user/dto/SendGiftDetailRes.java
Labels: feature

#150 [Fix] ShopOwner URL 주소를 수정한다.
  src/main/java/com/shallwe/domain/shopowner/presentation/ShopOwnerController.java
Labels: bug

#153 [FIX] Reservation Entitiy 스펙 변경으로 인한 Type 오류 해결
  src/main/java/com/shallwe/domain/memoryphoto/application/MemoryPhotoServiceImpl.java
  src/main/java/com/shallwe/domain/memoryphoto/dto/MemoryPhotoDetailRes.java
  src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationRepository.java
Labels: fix

#161 [FIX] 사장님 비밀번호 변경 API Auth 도메인으로 이동
  src/main/java/com/shallwe/domain/auth/application/AuthService.java
  src/main/java/com/shallwe/domain/auth/dto/ShopOwnerChangePasswordReq.java
  src/main/java/com/shallwe/domain/auth/presentation/AuthController.java
  src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerService.java
  src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerServiceImpl.java
  src/main/java/com/shallwe/domain/shopowner/presentation/ShopOwnerController.java
Labels: fix

#160 [FIX] User 회원 탈퇴 로직 변경
  src/main/java/com/shallwe/domain/auth/application/AuthService.java
  src/main/java/com/shallwe/domain/user/application/UserService.java
  src/main/java/com/shallwe/domain/user/application/UserServiceImpl.java
  src/main/java/com/shallwe/domain/user/presentation/UserController.java
Labels: fix

#164 [FIX] 삭제 된 유저 조회 시 NullPointException 현상 해결
  src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationQuerydslRepository.java
  src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationQuerydslRepositoryImpl.java
  src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationRepository.java
  src/main/java/com/shallwe/domain/user/application/UserServiceImpl.java
  src/main/java/com/shallwe/domain/user/dto/ReceiveGiftDetailRes.java
  src/main/java/com/shallwe/domain/user/dto/SendGiftDetailRes.java
  src/main/java/com/shallwe/domain/user/dto/UserDetailRes.java
Labels: bug, fix

#167 [Feat] 관리자 경험 선물 수정, 삭제 api 기능구현
  src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftService.java
  src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftServiceImpl.java
  src/main/java/com/shallwe/domain/experiencegift/domain/ExperienceGift.java
  src/main/java/com/shallwe/domain/experiencegift/domain/repository/ExperienceGiftQuerydslRepositoryImpl.java
  src/main/java/com/shallwe/domain/experiencegift/domain/repository/ExperienceGiftRepository.java
  src/main/java/com/shallwe/domain/experiencegift/dto/request/AdminExperienceReq.java
  src/main/java/com/shallwe/domain/experiencegift/presentation/AdminExperienceGiftController.java
Labels: feature, fix

#169 [Fix] 썸네일 사진 여려장 첨부 가능하도록 로직 수정
  src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftService.java
  src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftServiceImpl.java
  src/main/java/com/shallwe/domain/experiencegift/domain/ExperienceGift.java
  src/main/java/com/shallwe/domain/experiencegift/domain/ExperienceGiftImg.java
  src/main/java/com/shallwe/domain/experiencegift/domain/repository/ExperienceGiftImgRepository.java
  src/main/java/com/shallwe/domain/experiencegift/dto/request/AdminExperienceReq.java
  src/main/java/com/shallwe/domain/experiencegift/dto/response/ExperienceDetailRes.java
  src/main/java/com/shallwe/domain/experiencegift/dto/response/ExperienceExpCategoryRes.java
  src/main/java/com/shallwe/domain/experiencegift/dto/response/ExperienceRes.java
  src/main/java/com/shallwe/domain/experiencegift/dto/response/ExperienceSttCategoryRes.java
  src/main/java/com/shallwe/domain/experiencegift/presentation/ExperienceGiftController.java
Labels: fix

#170 [Hotfix] 충돌 해결, 관리자 상품 수정 api수정
  src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftServiceImpl.java
  src/main/java/com/shallwe/domain/experiencegift/domain/ExperienceGift.java
  src/main/java/com/shallwe/domain/experiencegift/domain/repository/ExperienceGiftImgRepository.java
  src/main/java/com/shallwe/domain/experiencegift/domain/repository/ExplanationRepository.java
Labels: bug

#171 [FEAT] 회원 탈퇴 시 불편사항도 같이 등록하도록 수정
  src/main/java/com/shallwe/domain/user/application/UserService.java
  src/main/java/com/shallwe/domain/user/application/UserServiceImpl.java
  src/main/java/com/shallwe/domain/user/domain/Complain.java
  src/main/java/com/shallwe/domain/user/domain/repository/ComplainRepository.java
  src/main/java/com/shallwe/domain/user/dto/PostComplainReq.java
  src/main/java/com/shallwe/domain/user/presentation/UserController.java
Labels: feature

#172 [Fix] 선물 등록 유의사항 컬럼 등록
  src/main/java/com/shallwe/domain/experiencegift/domain/ExperienceGift.java
  src/main/java/com/shallwe/domain/experiencegift/dto/request/AdminExperienceReq.java
Labels: chore

#174 가능 시간대 API반환값을 수정한다.
  src/main/java/com/shallwe/domain/reservation/presentation/ReservationController.java
  src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerService.java
  src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerServiceImpl.java
Labels: chore

#175 [Fix] 관리자 경험 선물 등록 reqeust 타입 수정, url->key로 수정
  src/main/java/com/shallwe/domain/experiencegift/dto/request/AdminExperienceReq.java
  src/main/java/com/shallwe/domain/experiencegift/dto/request/ExplanationReq.java
Labels: chore

#176 [Chore] toDto클래스도 url->key로 변경
  src/main/java/com/shallwe/domain/experiencegift/domain/Explanation.java
Labels: chore

#178 Reservation Entity NotNull 어노테이션 삭제
  src/main/java/com/shallwe/domain/reservation/domain/Reservation.java
Labels: chore

#180 상품ID, 날짜로 예약을 조회한다.
  src/main/java/com/shallwe/domain/reservation/application/ReservationService.java
  src/main/java/com/shallwe/domain/reservation/application/ReservationServiceImpl.java
  src/main/java/com/shallwe/domain/reservation/domain/Reservation.java
  src/main/java/com/shallwe/domain/reservation/domain/ReservationStatus.java
  src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationRepository.java
  src/main/java/com/shallwe/domain/reservation/presentation/ReservationController.java
  src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerService.java
  src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerServiceImpl.java
  src/main/java/com/shallwe/domain/shopowner/domain/repository/ShopOwnerRepository.java
  src/main/java/com/shallwe/domain/shopowner/presentation/ShopOwnerController.java
Labels: feature
