Repository ShallWeProject/ShallWeProject_Server, pull requests merged in 2023-09, with the labels that each got.

#112 fix: MemoryPhoto 조회 date 형식 yyyy-MM-dd HH:mm 으로 고정
  src/main/java/com/shallwe/domain/memoryPhoto/presentation/MemoryPhotoController.java
Labels: fix

#115 fix: 받은 선물 / 보낸 선물 DTO 수정
  src/main/java/com/shallwe/domain/user/application/UserService.java
  src/main/java/com/shallwe/domain/user/application/UserServiceImpl.java
  src/main/java/com/shallwe/domain/user/dto/ReceiveGiftDetailRes.java
  src/main/java/com/shallwe/domain/user/dto/SendAndReceiveGiftDetailRes.java
  src/main/java/com/shallwe/domain/user/dto/SendAndReceiveGiftListRes.java
  src/main/java/com/shallwe/domain/user/dto/SendGiftDetailRes.java
  src/main/java/com/shallwe/domain/user/presentation/UserController.java
Labels: fix

#116 chore: swagger 수정
  src/main/java/com/shallwe/domain/user/presentation/UserController.java
Labels: chore

#122 refactor: UserPrinciple로 User 객체 바로 가져올 수 있게 수정
  src/main/java/com/shallwe/domain/auth/application/CustomUserDetailsService.java
  src/main/java/com/shallwe/domain/user/application/UserServiceImpl.java
  src/main/java/com/shallwe/global/config/security/token/UserPrincipal.java
Labels: refactor

#124 refactor: MemoryPhoto API Response 수정 및 요청 파라미터 date 형식 변경
  src/main/java/com/shallwe/domain/memoryphoto/application/MemoryPhotoService.java
  src/main/java/com/shallwe/domain/memoryphoto/application/MemoryPhotoServiceImpl.java
  src/main/java/com/shallwe/domain/memoryphoto/dto/MemoryPhotoDetailRes.java
  src/main/java/com/shallwe/domain/memoryphoto/presentation/MemoryPhotoController.java
  src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationRepository.java
Labels: refactor, fix

#127 GitHub Action CI/CD 구축
  .github/workflows/github-actions.yml
  Dockerfile
  Dockerfile-dev
  src/main/java/com/shallwe/ShallWeApplication.java
  src/main/java/com/shallwe/domain/experiencegift/domain/repository/ExperienceGiftQuerydslRepositoryImpl.java
  src/main/resources/database/application-dev.yml
Labels: architecture
