Repository ShallWeProject/ShallWeProject_Server, pull requests merged in 2024-01, with the labels that each got.

#203 fix:관리자 경험 선물 등록, 수정 api 변경 / thumnail컬럼 삭제
  src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftServiceImpl.java
  src/main/java/com/shallwe/domain/experiencegift/domain/ExperienceGift.java
  src/main/java/com/shallwe/domain/experiencegift/dto/request/ExperienceReq.java
  src/main/java/com/shallwe/domain/experiencegift/dto/request/ShopOwnerExperienceReq.java
  src/main/java/com/shallwe/domain/experiencegift/dto/response/ExperienceRes.java
Labels: fix

#204 #201 refactor:필요없는 res 컬럼 삭제
  src/main/java/com/shallwe/domain/experiencegift/dto/response/ExperienceDetailRes.java
  src/main/java/com/shallwe/domain/experiencegift/dto/response/ExperienceSttCategoryRes.java
Labels: refactor

#205 예약 도메인 코드 리팩토링을 진행한다.
  src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftServiceImpl.java
  src/main/java/com/shallwe/domain/memoryphoto/application/MemoryPhotoServiceImpl.java
  src/main/java/com/shallwe/domain/reservation/application/ReservationCheckService.java
  src/main/java/com/shallwe/domain/reservation/application/ReservationCheckServiceImpl.java
  src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationService.java
  src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationServiceImpl.java
  src/main/java/com/shallwe/domain/reservation/application/ReservationService.java
  src/main/java/com/shallwe/domain/reservation/application/ReservationServiceImpl.java
  src/main/java/com/shallwe/domain/reservation/domain/Reservation.java
  src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationMemoryPhotoRepository.java
  src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationRepository.java
  src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationShopOwnerRepository.java
  src/main/java/com/shallwe/domain/reservation/dto/ReservationIdOwnerRes.java
  src/main/java/com/shallwe/domain/reservation/dto/ReservationRequest.java
  src/main/java/com/shallwe/domain/reservation/dto/ReservationUserReq.java
  src/main/java/com/shallwe/domain/reservation/dto/ValidTimeSlotRes.java
  src/main/java/com/shallwe/domain/reservation/dto/request/OwnerReservationCreate.java
  src/main/java/com/shallwe/domain/reservation/dto/request/UpdateReservationReq.java
  src/main/java/com/shallwe/domain/reservation/dto/request/UserReservationCreate.java
  src/main/java/com/shallwe/domain/reservation/dto/response/DeleteReservationRes.java
  src/main/java/com/shallwe/domain/reservation/dto/response/ReservationIdOwnerRes.java
  src/main/java/com/shallwe/domain/reservation/dto/response/ReservationIdUserRes.java
  src/main/java/com/shallwe/domain/reservation/dto/response/ReservationResponse.java
  src/main/java/com/shallwe/domain/reservation/dto/response/ValidTimeSlotRes.java
  src/main/java/com/shallwe/domain/reservation/presentation/ReservationController.java
  src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerService.java
  src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerServiceImpl.java
  src/main/java/com/shallwe/domain/shopowner/presentation/ShopOwnerController.java
Labels: refactor

#207 병합 충돌을 해결한다.
  src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftServiceImpl.java
  src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationServiceImpl.java
  src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationQuerydslRepositoryImpl.java
Labels: bug, fix

#209 컬럼명을 수정한다.
  src/main/java/com/shallwe/domain/reservation/domain/Reservation.java
Labels: bug

#215 feat:사장님 앱 경험 선물 상세 조회 API
  src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftService.java
  src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftServiceImpl.java
  src/main/java/com/shallwe/domain/experiencegift/domain/repository/ExperienceGiftRepository.java
  src/main/java/com/shallwe/domain/experiencegift/dto/response/ShopOwnerExperienceDetailsRes.java
  src/main/java/com/shallwe/domain/experiencegift/presentation/ShopOwnerExperienceGiftController.java
Labels: feature

#216 [REFACTOR]: RestTemplate 관련 Refactoring
  .gitignore
  src/main/java/com/shallwe/ShallWeApplication.java
  src/main/java/com/shallwe/domain/auth/dto/SmsReq.java
  src/main/java/com/shallwe/domain/auth/presentation/AuthController.java
  src/main/java/com/shallwe/global/config/SwaggerConfig.java
  src/main/java/com/shallwe/global/config/resttemplate/RestTemplateClientHttpRequestInterceptor.java
  src/main/java/com/shallwe/global/config/resttemplate/RestTemplateConfig.java
  src/main/java/com/shallwe/global/config/resttemplate/RestTemplateErrorHandler.java
  src/main/java/com/shallwe/global/infrastructure/sms/NaverSmsClient.java
  src/main/java/com/shallwe/global/infrastructure/sms/SmsClient.java
  src/main/java/com/shallwe/global/infrastructure/sms/dto/NaverVerifySmsReq.java
  src/main/java/com/shallwe/global/infrastructure/sms/exception/InvalidPhoneNumberException.java
  src/main/java/com/shallwe/global/infrastructure/sms/exception/InvalidVerificationCodeException.java
  src/main/java/com/shallwe/global/infrastructure/sms/exception/TimeOutException.java
Labels: refactor

#218 [FIX]: JasyptConfig.java 제거
  build.gradle
  src/main/java/com/shallwe/global/config/JasyptConfig.java
Labels: fix

#220 사장님 예약 추가시 ownerID 제거한다.
  src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationServiceImpl.java
  src/main/java/com/shallwe/domain/reservation/dto/request/OwnerReservationCreate.java
Labels: chore

#222 [DEPENDENCY] FowardedHeaderFilter를 위한 Spring 3.2.2 버전 업
  build.gradle
  src/main/java/com/shallwe/global/config/security/SecurityConfig.java
Labels: devops

#224 feat: Local SSH Tunneling to RDS 설정
  build.gradle
  src/main/java/com/shallwe/global/config/ssh/SshDataSourceConfig.java
  src/main/java/com/shallwe/global/config/ssh/SshTunnelingInitializer.java
  src/main/resources/application-ebprod.yml
  src/main/resources/cloud/application-navercloud.yml
  src/main/resources/cloud/application-s3file.yml
  src/main/resources/database/application-dev.yml
  src/main/resources/oauth2/application-oauth2.yml
  src/main/resources/swagger/application-springdoc.yml
Labels: devops

#227 infra: prod deploy script 작성
  .github/workflows/dev-cicd.yml
  .github/workflows/prod-cicd.yml
  .gitignore
Labels: devops

#228 fix: Dockerfile-prod 구성
  Dockerfile
  Dockerfile-prod
Labels: devops

#231 chore: deploy script 수정
  .github/workflows/dev-cicd.yml
  .github/workflows/prod-cicd.yml
  src/main/java/com/shallwe/ShallWeApplication.java
Labels: chore

#233 infra: cors설정
  src/main/java/com/shallwe/global/config/WebConfig.java
Labels: infra

#236 fix: cors수정
  src/main/java/com/shallwe/global/config/WebConfig.java
Labels: fix, infra

#237 fix: core 설정 변경
  src/main/java/com/shallwe/global/config/WebConfig.java
Labels: chore, infra

#242 사장 예약 추가시 조회 레포지토리를 변경한다.
  src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationServiceImpl.java
Labels: fix

#243 배포 서버 <- 개발 서버 병합
  src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationServiceImpl.java
Labels: infra

#244 모니터링 종속성을 추가한다.
  build.gradle
Labels: infra
