Repository ShallWeProject/ShallWeProject_Server, pull requests merged in 2024-03, with the labels that each got.

#277 feat: 애플 회원가입 / 로그인 구현 및 RestClient 도입
  build.gradle
  src/main/java/com/shallwe/domain/auth/application/AuthService.java
  src/main/java/com/shallwe/domain/auth/application/CustomDefaultOAuth2UserService.java
  src/main/java/com/shallwe/domain/auth/application/CustomTokenProviderService.java
  src/main/java/com/shallwe/domain/auth/domain/AppleToken.java
  src/main/java/com/shallwe/domain/auth/domain/Token.java
  src/main/java/com/shallwe/domain/auth/domain/repository/AppleTokenRepository.java
  src/main/java/com/shallwe/domain/auth/domain/repository/CustomAuthorizationRequestRepository.java
  src/main/java/com/shallwe/domain/auth/dto/MessageMapping.java
  src/main/java/com/shallwe/domain/auth/dto/request/AppleSignInReq.java
  src/main/java/com/shallwe/domain/auth/dto/request/AppleSignUpReq.java
  src/main/java/com/shallwe/domain/auth/dto/request/AppleTokenReq.java
  src/main/java/com/shallwe/domain/auth/dto/request/NaverCloudSmsReq.java
  src/main/java/com/shallwe/domain/auth/dto/request/RefreshTokenReq.java
  src/main/java/com/shallwe/domain/auth/dto/request/ShopOwnerChangePasswordReq.java
  src/main/java/com/shallwe/domain/auth/dto/request/ShopOwnerSignInReq.java
  src/main/java/com/shallwe/domain/auth/dto/request/ShopOwnerSignUpReq.java
  src/main/java/com/shallwe/domain/auth/dto/request/SignInReq.java
  src/main/java/com/shallwe/domain/auth/dto/request/SignUpReq.java
  src/main/java/com/shallwe/domain/auth/dto/request/ValidVerificationCodeReq.java
  src/main/java/com/shallwe/domain/auth/dto/response/ApplePublicKeyRes.java
  src/main/java/com/shallwe/domain/auth/dto/response/AppleSignInRes.java
  src/main/java/com/shallwe/domain/auth/dto/response/AuthRes.java
  src/main/java/com/shallwe/domain/auth/dto/response/NaverCloudSmsRes.java
  src/main/java/com/shallwe/domain/auth/dto/response/SmsResponseDto.java
  src/main/java/com/shallwe/domain/auth/exception/AlreadyExistsProviderIdException.java
  src/main/java/com/shallwe/domain/auth/presentation/AuthController.java
  src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationQuerydslRepositoryImpl.java
  src/main/java/com/shallwe/domain/user/domain/User.java
  src/main/java/com/shallwe/domain/user/domain/repository/UserRepository.java
  src/main/java/com/shallwe/domain/user/dto/UserDetailRes.java
  src/main/java/com/shallwe/global/config/FeignConfig.java
  src/main/java/com/shallwe/global/config/resttemplate/RestTemplateClientHttpRequestInterceptor.java
  src/main/java/com/shallwe/global/config/resttemplate/RestTemplateConfig.java
  src/main/java/com/shallwe/global/config/resttemplate/RestTemplateErrorHandler.java
  src/main/java/com/shallwe/global/config/security/AuthConfig.java
  src/main/java/com/shallwe/global/config/security/handler/CustomSimpleUrlAuthenticationFailureHandler.java
  src/main/java/com/shallwe/global/config/security/handler/CustomSimpleUrlAuthenticationSuccessHandler.java
  src/main/java/com/shallwe/global/infrastructure/feign/apple/AppleClient.java
  src/main/java/com/shallwe/global/infrastructure/sms/NaverSmsClient.java
  src/main/java/com/shallwe/global/infrastructure/sms/SmsClient.java
  src/main/java/com/shallwe/global/utils/AppleJwtUtils.java
  src/main/java/com/shallwe/global/utils/CustomCookie.java
Labels: feature, refactor

#280 fix: 애플 로그인 로직 수정
  src/main/java/com/shallwe/domain/auth/application/AuthService.java
  src/main/java/com/shallwe/domain/auth/dto/request/AppleSignInReq.java
  src/main/java/com/shallwe/domain/auth/exception/UnRegisteredUserException.java
  src/main/java/com/shallwe/domain/auth/presentation/AuthController.java
Labels: fix

#281 fix: 애플 로그인 로직 수정
  src/main/java/com/shallwe/domain/auth/application/AuthService.java
  src/main/java/com/shallwe/domain/auth/dto/request/AppleSignUpReq.java
  src/main/java/com/shallwe/domain/auth/dto/response/AppleSignInRes.java
  src/main/java/com/shallwe/domain/auth/presentation/AuthController.java
  src/main/java/com/shallwe/domain/user/application/UserService.java
  src/main/java/com/shallwe/domain/user/application/UserServiceImpl.java
  src/main/java/com/shallwe/domain/user/dto/SignUpUserReq.java
  src/main/java/com/shallwe/domain/user/presentation/UserController.java
Labels: chore, fix

#282 deploy: Prod 서버 배포
  src/main/java/com/shallwe/domain/auth/application/AuthService.java
  src/main/java/com/shallwe/domain/auth/dto/request/AppleSignInReq.java
  src/main/java/com/shallwe/domain/auth/dto/request/AppleSignUpReq.java
  src/main/java/com/shallwe/domain/auth/dto/response/AppleSignInRes.java
  src/main/java/com/shallwe/domain/auth/exception/UnRegisteredUserException.java
  src/main/java/com/shallwe/domain/auth/presentation/AuthController.java
  src/main/java/com/shallwe/domain/user/application/UserService.java
  src/main/java/com/shallwe/domain/user/application/UserServiceImpl.java
  src/main/java/com/shallwe/domain/user/dto/SignUpUserReq.java
  src/main/java/com/shallwe/domain/user/presentation/UserController.java
Labels: chore, fix

#284 feat: 알림톡 기능 구현 / 예약등록 알림톡 적용
  src/main/java/com/shallwe/domain/auth/dto/request/NaverCloudSmsReq.java
  src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftServiceImpl.java
  src/main/java/com/shallwe/domain/experiencegift/domain/repository/ExperienceGiftRepository.java
  src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationService.java
  src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationServiceImpl.java
  src/main/java/com/shallwe/domain/reservation/domain/Reservation.java
  src/main/java/com/shallwe/domain/reservation/dto/request/OwnerReservationCreate.java
  src/main/java/com/shallwe/domain/reservation/dto/response/ReservationResponse.java
  src/main/java/com/shallwe/domain/reservation/presentation/ReservationController.java
  src/main/java/com/shallwe/domain/shopowner/domain/ShopOwner.java
  src/main/java/com/shallwe/global/infrastructure/sms/NaverSmsClient.java
  src/main/java/com/shallwe/global/infrastructure/sms/dto/AlimTalkReq.java
  src/main/java/com/shallwe/global/infrastructure/sms/dto/MessageMapping.java
Labels: feature

#286 feat: 알림톡 기능 구현
  src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationService.java
  src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationServiceImpl.java
  src/main/java/com/shallwe/domain/reservation/domain/Reservation.java
  src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationRepository.java
  src/main/java/com/shallwe/domain/reservation/exception/NotAvailableReservationStatusException.java
  src/main/java/com/shallwe/domain/reservation/exception/UserReservationMismatchException.java
  src/main/java/com/shallwe/domain/reservation/presentation/ReservationController.java
  src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerService.java
  src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerServiceImpl.java
  src/main/java/com/shallwe/domain/shopowner/exception/NotReservedException.java
  src/main/java/com/shallwe/domain/shopowner/exception/ShopOwnerExperienceGiftMismatchException.java
  src/main/java/com/shallwe/domain/shopowner/presentation/ShopOwnerController.java
  src/main/java/com/shallwe/global/infrastructure/sms/NaverSmsClient.java
Labels: feature

#287 예약 관련 로직을 수정한다.
  .gitignore
  src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationServiceImpl.java
  src/main/java/com/shallwe/domain/reservation/domain/Reservation.java
  src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationRepository.java
  src/main/java/com/shallwe/domain/reservation/exception/InvalidReservationUpdateException.java
  src/main/java/com/shallwe/domain/reservation/presentation/ReservationController.java
Labels: feature

#290 feat: 알림톡 기능 적용
  .gitignore
  src/main/java/com/shallwe/domain/auth/dto/request/NaverCloudSmsReq.java
  src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftServiceImpl.java
  src/main/java/com/shallwe/domain/experiencegift/domain/repository/ExperienceGiftRepository.java
  src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationService.java
  src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationServiceImpl.java
  src/main/java/com/shallwe/domain/reservation/domain/Reservation.java
  src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationRepository.java
  src/main/java/com/shallwe/domain/reservation/dto/request/OwnerReservationCreate.java
  src/main/java/com/shallwe/domain/reservation/dto/request/UpdateReservationReq.java
  src/main/java/com/shallwe/domain/reservation/dto/response/ReservationResponse.java
  src/main/java/com/shallwe/domain/reservation/exception/InvalidReservationUpdateException.java
  src/main/java/com/shallwe/domain/reservation/exception/NotAvailableReservationStatusException.java
  src/main/java/com/shallwe/domain/reservation/exception/UserReservationMismatchException.java
  src/main/java/com/shallwe/domain/reservation/presentation/ReservationController.java
  src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerService.java
  src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerServiceImpl.java
  src/main/java/com/shallwe/domain/shopowner/domain/ShopOwner.java
  src/main/java/com/shallwe/domain/shopowner/exception/NotReservedException.java
  src/main/java/com/shallwe/domain/shopowner/exception/ShopOwnerExperienceGiftMismatchException.java
  src/main/java/com/shallwe/domain/shopowner/presentation/ShopOwnerController.java
  src/main/java/com/shallwe/global/infrastructure/sms/NaverSmsClient.java
  src/main/java/com/shallwe/global/infrastructure/sms/dto/AlimTalkReq.java
  src/main/java/com/shallwe/global/infrastructure/sms/dto/MessageMapping.java
Labels: feature

#291 fix: 예약 등록 알림톡 오류 수정
  src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationRepository.java
  src/main/java/com/shallwe/global/infrastructure/sms/NaverSmsClient.java
Labels: fix

#292 fix: 예약 등록 알림톡 오류 수정 (#291)
  src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationRepository.java
  src/main/java/com/shallwe/global/infrastructure/sms/NaverSmsClient.java
Labels: fix

#294 fix: 예약 등록 시 Receiver한테 알림톡 가는 현상 수정 (#293)
  src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationServiceImpl.java
  src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationRepository.java
  src/main/java/com/shallwe/global/infrastructure/sms/NaverSmsClient.java
Labels: fix

#296 fix: 사장님은 예약중인 상태만 조회할 수 있도록 수정
  src/main/java/com/shallwe/domain/reservation/application/ReservationCheckServiceImpl.java
  src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationRepository.java
Labels: fix

#297 fix: 카카오/구글 로그인 로직 수정
  src/main/java/com/shallwe/domain/auth/application/AuthService.java
  src/main/java/com/shallwe/domain/auth/application/CustomDefaultOAuth2UserService.java
  src/main/java/com/shallwe/domain/auth/domain/OAuth2Token.java
  src/main/java/com/shallwe/domain/auth/domain/RefreshToken.java
  src/main/java/com/shallwe/domain/auth/domain/repository/AppleTokenRepository.java
  src/main/java/com/shallwe/domain/auth/domain/repository/OAuth2TokenRepository.java
  src/main/java/com/shallwe/domain/auth/domain/repository/RefreshTokenRepository.java
  src/main/java/com/shallwe/domain/auth/domain/repository/TokenRepository.java
  src/main/java/com/shallwe/domain/auth/dto/request/SignInReq.java
  src/main/java/com/shallwe/domain/auth/dto/request/SignUpReq.java
  src/main/java/com/shallwe/domain/auth/dto/response/SignInRes.java
  src/main/java/com/shallwe/domain/auth/presentation/AuthController.java
  src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerServiceImpl.java
  src/main/java/com/shallwe/domain/user/application/UserServiceImpl.java
  src/main/java/com/shallwe/global/config/security/SecurityConfig.java
  src/main/java/com/shallwe/global/config/security/handler/CustomSimpleUrlAuthenticationFailureHandler.java
  src/main/java/com/shallwe/global/config/security/handler/CustomSimpleUrlAuthenticationSuccessHandler.java
Labels: fix

#298 fix: 카카오/구글 로그인 API 통합
  src/main/java/com/shallwe/domain/auth/application/AuthService.java
  src/main/java/com/shallwe/domain/auth/application/CustomDefaultOAuth2UserService.java
  src/main/java/com/shallwe/domain/auth/domain/OAuth2Token.java
  src/main/java/com/shallwe/domain/auth/domain/RefreshToken.java
  src/main/java/com/shallwe/domain/auth/domain/repository/AppleTokenRepository.java
  src/main/java/com/shallwe/domain/auth/domain/repository/OAuth2TokenRepository.java
  src/main/java/com/shallwe/domain/auth/domain/repository/RefreshTokenRepository.java
  src/main/java/com/shallwe/domain/auth/domain/repository/TokenRepository.java
  src/main/java/com/shallwe/domain/auth/dto/request/SignInReq.java
  src/main/java/com/shallwe/domain/auth/dto/request/SignUpReq.java
  src/main/java/com/shallwe/domain/auth/dto/response/SignInRes.java
  src/main/java/com/shallwe/domain/auth/presentation/AuthController.java
  src/main/java/com/shallwe/domain/reservation/application/ReservationCheckServiceImpl.java
  src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationRepository.java
  src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerServiceImpl.java
  src/main/java/com/shallwe/domain/user/application/UserServiceImpl.java
  src/main/java/com/shallwe/global/config/security/SecurityConfig.java
  src/main/java/com/shallwe/global/config/security/handler/CustomSimpleUrlAuthenticationFailureHandler.java
  src/main/java/com/shallwe/global/config/security/handler/CustomSimpleUrlAuthenticationSuccessHandler.java
Labels: fix

#299 fix: findByProviderId Status.ACTIVE 조건 추가
  src/main/java/com/shallwe/domain/auth/application/AuthService.java
  src/main/java/com/shallwe/domain/user/domain/repository/UserRepository.java
Labels: fix

#300 fix: findByProviderId Status.ACTIVE 조건 추가 (#299)
  src/main/java/com/shallwe/domain/auth/application/AuthService.java
  src/main/java/com/shallwe/domain/user/domain/repository/UserRepository.java
Labels: fix

#301 test: 인증번호 전송 Test
  src/main/java/com/shallwe/domain/auth/domain/repository/OAuth2TokenRepository.java
  src/main/java/com/shallwe/domain/auth/dto/request/AppleTokenRevokeReq.java
  src/main/java/com/shallwe/domain/auth/exception/InvalidOAuth2RefreshTokenException.java
  src/main/java/com/shallwe/domain/auth/presentation/AuthController.java
  src/main/java/com/shallwe/domain/user/application/UserService.java
  src/main/java/com/shallwe/domain/user/application/UserServiceImpl.java
  src/main/java/com/shallwe/domain/user/presentation/UserController.java
  src/main/java/com/shallwe/global/config/security/AuthConfig.java
  src/main/java/com/shallwe/global/infrastructure/sms/NaverSmsClient.java
  src/main/java/com/shallwe/global/utils/AppleJwtUtils.java
Labels: test
