Repository ShallWeProject/ShallWeProject_Server, pull requests merged in 2024-02, with the labels that each got.

#245 모니터링 관련 시큐리티 설정을 변경한다.
  src/main/java/com/shallwe/global/config/security/SecurityConfig.java
Labels: devops

#246 CD시 Shallwe-Application 만 변경하도록 수정한다.
  .github/workflows/dev-cicd.yml
  src/main/java/com/shallwe/domain/reservation/presentation/ReservationController.java
  src/main/java/com/shallwe/global/config/security/SecurityConfig.java
Labels: devops

#248 hotfix: Explation img response AwsS3Util 제거
  src/main/java/com/shallwe/domain/experiencegift/dto/response/ExplanationRes.java
Labels: hotfix

#249 hotfix: explationres todto 메소드 AwsS3Util 삭제
  .github/workflows/dev-cicd.yml
  build.gradle
  src/main/java/com/shallwe/domain/experiencegift/dto/response/ExplanationRes.java
  src/main/java/com/shallwe/domain/reservation/presentation/ReservationController.java
  src/main/java/com/shallwe/global/config/security/SecurityConfig.java
Labels: hotfix

#250 hotfix: Reservation 등록 API 오류 수정
  src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationServiceImpl.java
  src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationRepository.java
Labels: fix

#251 hotfix: Reservation 등록 API 오류 수정 (#250)
  src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationServiceImpl.java
  src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationRepository.java
Labels: hotfix

#253 hotfix: 받은 선물 탈퇴한 회원 조회 안되는 현상 수정 (#252)
  src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationQuerydslRepository.java
  src/main/java/com/shallwe/domain/reservation/domain/repository/ReservationQuerydslRepositoryImpl.java
  src/main/java/com/shallwe/domain/user/application/UserServiceImpl.java
  src/main/java/com/shallwe/domain/user/domain/User.java
  src/main/java/com/shallwe/domain/user/dto/ReceiveGiftDetailRes.java
  src/main/java/com/shallwe/domain/user/dto/SendGiftDetailRes.java
  src/main/java/com/shallwe/domain/user/dto/UserDetailRes.java
Labels: hotfix

#254 fix: User Authorization 상태 값 오류 수정
  src/main/java/com/shallwe/domain/auth/application/AuthService.java
  src/main/java/com/shallwe/domain/auth/application/CustomDefaultOAuth2UserService.java
  src/main/java/com/shallwe/domain/auth/application/CustomUserDetailsService.java
  src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationServiceImpl.java
  src/main/java/com/shallwe/domain/shopowner/domain/repository/ShopOwnerRepository.java
  src/main/java/com/shallwe/domain/user/domain/repository/UserRepository.java
  src/main/java/com/shallwe/domain/user/dto/UserDetailRes.java
Labels: fix

#255 hotfix: User Authorization 상태 값 오류 수정 (#254)
  src/main/java/com/shallwe/domain/auth/application/AuthService.java
  src/main/java/com/shallwe/domain/auth/application/CustomDefaultOAuth2UserService.java
  src/main/java/com/shallwe/domain/auth/application/CustomUserDetailsService.java
  src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationServiceImpl.java
  src/main/java/com/shallwe/domain/shopowner/domain/repository/ShopOwnerRepository.java
  src/main/java/com/shallwe/domain/user/domain/repository/UserRepository.java
  src/main/java/com/shallwe/domain/user/dto/UserDetailRes.java
Labels: hotfix

#257 chore: 경험 선물 상세 API note 컬럼 추가
  src/main/java/com/shallwe/domain/experiencegift/dto/response/ExperienceDetailRes.java
  src/main/java/com/shallwe/domain/user/domain/User.java
Labels: chore

#258 chore: 경험 선물 상세 API note 컬럼 추가 (#257)
  src/main/java/com/shallwe/domain/experiencegift/dto/response/ExperienceDetailRes.java
  src/main/java/com/shallwe/domain/user/domain/User.java
Labels: chore

#259 ID 반환시 NPE를 해결한다
  src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationServiceImpl.java
Labels: chore

#263 fix: shopOwner reservationList 어노테이션 수정
  src/main/java/com/shallwe/domain/shopowner/domain/ShopOwner.java
Labels: fix

#265 feat: 경험 상품 조회 페이징 API 구현
  src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftService.java
  src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftServiceImpl.java
  src/main/java/com/shallwe/domain/experiencegift/domain/ExperienceGift.java
  src/main/java/com/shallwe/domain/experiencegift/domain/ExperienceGiftExperienceCategory.java
  src/main/java/com/shallwe/domain/experiencegift/domain/ExperienceGiftSituationCategory.java
  src/main/java/com/shallwe/domain/experiencegift/domain/repository/ExperienceGiftQuerydslRepository.java
  src/main/java/com/shallwe/domain/experiencegift/domain/repository/ExperienceGiftQuerydslRepositoryImpl.java
  src/main/java/com/shallwe/domain/experiencegift/dto/response/ExperienceGiftRes.java
  src/main/java/com/shallwe/domain/experiencegift/presentation/ExperienceGiftV2Controller.java
  src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationService.java
  src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationServiceImpl.java
  src/main/java/com/shallwe/domain/reservation/domain/Reservation.java
  src/main/java/com/shallwe/domain/reservation/presentation/ReservationController.java
  src/main/java/com/shallwe/domain/user/domain/User.java
  src/main/java/com/shallwe/global/config/Constant.java
Labels: feature, fix

#266 feat: 경험 선물 조회 Paging API 구현
  src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftService.java
  src/main/java/com/shallwe/domain/experiencegift/application/ExperienceGiftServiceImpl.java
  src/main/java/com/shallwe/domain/experiencegift/domain/ExperienceGift.java
  src/main/java/com/shallwe/domain/experiencegift/domain/ExperienceGiftExperienceCategory.java
  src/main/java/com/shallwe/domain/experiencegift/domain/ExperienceGiftSituationCategory.java
  src/main/java/com/shallwe/domain/experiencegift/domain/repository/ExperienceGiftQuerydslRepository.java
  src/main/java/com/shallwe/domain/experiencegift/domain/repository/ExperienceGiftQuerydslRepositoryImpl.java
  src/main/java/com/shallwe/domain/experiencegift/dto/response/ExperienceGiftRes.java
  src/main/java/com/shallwe/domain/experiencegift/presentation/ExperienceGiftV2Controller.java
  src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationService.java
  src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationServiceImpl.java
  src/main/java/com/shallwe/domain/reservation/domain/Reservation.java
  src/main/java/com/shallwe/domain/reservation/presentation/ReservationController.java
  src/main/java/com/shallwe/domain/shopowner/domain/ShopOwner.java
  src/main/java/com/shallwe/domain/user/domain/User.java
  src/main/java/com/shallwe/global/config/Constant.java
Labels: feature, fix

#267 feat: 애플 로그인 API 구현
  build.gradle
  src/main/java/com/shallwe/domain/auth/application/AuthService.java
  src/main/java/com/shallwe/domain/auth/application/CustomTokenProviderService.java
  src/main/java/com/shallwe/domain/auth/dto/AppleSignInReq.java
  src/main/java/com/shallwe/domain/auth/dto/AppleSignInRes.java
  src/main/java/com/shallwe/domain/auth/dto/SignUpReq.java
  src/main/java/com/shallwe/domain/auth/exception/UnRegisteredUserException.java
  src/main/java/com/shallwe/domain/auth/presentation/AuthController.java
  src/main/java/com/shallwe/domain/user/domain/Provider.java
  src/main/java/com/shallwe/global/config/FeignConfig.java
  src/main/java/com/shallwe/global/config/security/auth/OAuth2UserInfoFactory.java
  src/main/java/com/shallwe/global/config/security/auth/company/Kakao.java
  src/main/java/com/shallwe/global/infrastructure/feign/apple/AppleClient.java
  src/main/java/com/shallwe/global/infrastructure/feign/apple/dto/ApplePublicKeyRes.java
  src/main/java/com/shallwe/global/utils/AppleJwtUtils.java
Labels: feature

#268 feat: 애플 로그인 API 구현 (#267)
  build.gradle
  src/main/java/com/shallwe/domain/auth/application/AuthService.java
  src/main/java/com/shallwe/domain/auth/application/CustomTokenProviderService.java
  src/main/java/com/shallwe/domain/auth/dto/AppleSignInReq.java
  src/main/java/com/shallwe/domain/auth/dto/AppleSignInRes.java
  src/main/java/com/shallwe/domain/auth/dto/SignUpReq.java
  src/main/java/com/shallwe/domain/auth/exception/UnRegisteredUserException.java
  src/main/java/com/shallwe/domain/auth/presentation/AuthController.java
  src/main/java/com/shallwe/domain/user/domain/Provider.java
  src/main/java/com/shallwe/global/config/FeignConfig.java
  src/main/java/com/shallwe/global/config/security/auth/OAuth2UserInfoFactory.java
  src/main/java/com/shallwe/global/config/security/auth/company/Kakao.java
  src/main/java/com/shallwe/global/infrastructure/feign/apple/AppleClient.java
  src/main/java/com/shallwe/global/infrastructure/feign/apple/dto/ApplePublicKeyRes.java
  src/main/java/com/shallwe/global/utils/AppleJwtUtils.java
Labels: feature

#269 fix: Claims sub 항목으로 사용하게 수정
  src/main/java/com/shallwe/domain/auth/application/AuthService.java
  src/main/java/com/shallwe/domain/auth/dto/AppleSignInReq.java
  src/main/java/com/shallwe/domain/auth/dto/SignUpReq.java
  src/main/java/com/shallwe/domain/auth/exception/InvalidProviderIdException.java
  src/main/java/com/shallwe/domain/auth/presentation/AuthController.java
  src/main/java/com/shallwe/domain/user/domain/repository/UserRepository.java
Labels: fix

#270 fix: Claims sub 항목으로 사용하게 수정 (#269)
  src/main/java/com/shallwe/domain/auth/application/AuthService.java
  src/main/java/com/shallwe/domain/auth/dto/AppleSignInReq.java
  src/main/java/com/shallwe/domain/auth/dto/SignUpReq.java
  src/main/java/com/shallwe/domain/auth/exception/InvalidProviderIdException.java
  src/main/java/com/shallwe/domain/auth/presentation/AuthController.java
  src/main/java/com/shallwe/domain/user/domain/repository/UserRepository.java
Labels: fix

#272 예약 예외 분리하고 ENUM로직을 수정한다.
  src/main/java/com/shallwe/domain/memoryphoto/application/MemoryPhotoServiceImpl.java
  src/main/java/com/shallwe/domain/reservation/application/ReservationCheckServiceImpl.java
  src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationServiceImpl.java
  src/main/java/com/shallwe/domain/reservation/dto/request/OwnerReservationCreate.java
  src/main/java/com/shallwe/domain/reservation/exception/InvalidReceiverException.java
  src/main/java/com/shallwe/domain/reservation/exception/InvalidSenderException.java
  src/main/java/com/shallwe/domain/reservation/exception/InvalidUserException.java
  src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerServiceImpl.java
Labels: fix

#273 deploy: main develop 동기화
  src/main/java/com/shallwe/domain/memoryphoto/application/MemoryPhotoServiceImpl.java
  src/main/java/com/shallwe/domain/reservation/application/ReservationCheckServiceImpl.java
  src/main/java/com/shallwe/domain/reservation/application/ReservationManipulationServiceImpl.java
  src/main/java/com/shallwe/domain/reservation/dto/request/OwnerReservationCreate.java
  src/main/java/com/shallwe/domain/reservation/exception/InvalidReceiverException.java
  src/main/java/com/shallwe/domain/reservation/exception/InvalidSenderException.java
  src/main/java/com/shallwe/domain/reservation/exception/InvalidUserException.java
  src/main/java/com/shallwe/domain/shopowner/application/ShopOwnerServiceImpl.java
Labels: etc

#275 chore: Error Response 형식 수정
  src/main/java/com/shallwe/global/error/ApiControllerAdvice.java
  src/main/java/com/shallwe/global/payload/ResponseCustom.java
Labels: chore
